### PR TITLE
Add documentation for ConceptMap.js and add scrolling

### PR DESCRIPTION
**Pull request by Mehul-Gandhi**
Why am I making this change: This will help for the new users being onboarded to this concept map project.
Changes made: Add documentation to explain parts of the code. Add scrolling as requested.

User interface:
image
image
image

### CODE REVIEW

**Comment by Connor-Bernard** [comment]
Is there any way to avoid two scroll bars.  That was one thing we wanted to do previously

**Comment by Connor-Bernard** [comment]
tbh I still kinda think we should just use the react version and ditch the iframe, but that will functionally decouple the two projs 🤷‍♂️

**Comment by Connor-Bernard** [comment]
Also make sure you're tracking your work on Jira and linking it to your PR with your ticket id

**Comment by Connor-Bernard** [comment]
But thanks for being proactive

**Comment by Mehul-Gandhi** [comment]
New version. There is still an iframe, but there is one scrolling bar. However, the scrolling bar is too long, so there is a lot of unnecessary whitespace after the concept map iframe. 


image

**Comment by Mehul-Gandhi** [comment]
JIRA ticket: https://dashbd.atlassian.net/jira/software/projects/CM/boards/3?selectedIssue=CM-7

**Comment by Connor-Bernard** [comment]
See #160 for completed CM patch

**Review by Connor-Bernard — CHANGES_REQUESTED** [review]
You can make this add documentation but see #160 for the CM fix

**Pull request closed without merging**
