### PR TITLE
4 accordion style grade display

### PR DESCRIPTION
**Pull request by Madelen143**
First time writing in JS and using React so if there's anything you think I could change to be better then I would love to hear it please!

### CODE REVIEW

**Comment by Connor-Bernard** [comment]
I made a couple of edits (mostly just syntax and making the nested components into stand-alone components with their own files).

It looks really good though!  I think the only thing that I would mention is that it is really hard to see the boundaries of the accordion sections.  It also expands slightly up as well when expanding the accordion which looks kinda off for the topmost accordion.

As far as the implementation goes though, my only comment would be that I'm worried about the filtering method -- I know Dan wants us to make it as universal as possible, so I think he may object to things like filtering the exams by containing the letter 'i' (super creative btw).

Maybe we can brainstorm another way to filter them at some point.  My initial thought was to change the spreadsheet to include the type of assignment and we can pull that in as well using the API.  Let me know your thoughts though!

Oh and congrats on your first PR :)

**Comment by Madelen143** [comment]
I was worried that I was putting too much in one file and I agree, I hated filtering with something so specific but for the sake of having a fully functional view I went with it. I was also hoping we could make some changes to the spreadsheet! I'm not exactly sure what it looks like right now, I just made some assumptions based on how the data was being used with the DataGrid, but yes adding a more universal tag like "Exams" for all the midterms/finals would be a great help.

**Comment by Connor-Bernard** [comment]
## Minimizing file and creating new components

Yeah no worries at all, I'd say generally, if you are making a new component, it is good to define it as it's own file.  This allows for a bit more clarity in the file structure, but mainly ensures that the passage of data is done in a coherent way; for example, you will see that I changed up the passage of the props for the components that you were working on.  With them all in the same file, we were referencing the nonlocal gradeData from child components which ideally we would do by passing them through props.  It also ensures that all of the data handling is done in one spot which is important for properly rendering the components.

## Filtering

I spoke with Dan and he said that it is totally okay for us to make another row dedicated to saying what type of assignment it is so we don't have to filter by the actual assignment.  Again, props to your creativity in doing that though.  He is also going to send me over over his live data at some point soon so we can actually have a look at what his spreadsheet looks like and configure it (ideally) to his sheet to the furthest extent possible.  Also, I just shared the spreadsheet that this is based on with you so you can get a better idea of what it looks like.

**Review by Connor-Bernard — APPROVED** [review]
Looks good.  Actively works and implements the required changes.  Nice job @Madelen143

**Pull request merged**
